/* eslint-disable max-len */
import messages from "./messages";

const constants = {
  ROUTES: {
    HOME: "/home",
    CONTACT_US: "/contactUs",
    LOGIN: "/login",
    ONBOARD: "/onboard",
    EDITORG: "/editOrganization",
    VIEWONBOARD: "/viewOrganization",
    FORGOT_PASSWORD: "/forgotPassword",
    ACTIVATEACCOUNT: "/activateAccount",
    CHANGEPASSWORD: "/changePassword",
    RESETPASSWORD: "/resetPassword",
    ONBOARDEMPLOYEE: "/onboardEmployee",
    VIEWALLEMPLOYEE: "/viewEmployee",
    SETTINGS: "/settings",
    TERMSANDACONDITIONS: "/termsandConditions",
    PRIVACYPOLICY: "/privacyPolicy",
    COOKIEPREFERENCES: "/cookiePreferences",
    ORGERROR: "/orgnazationError",
    PASSWORDSUCCESS: "/passwordSuccess"
  },
  HTTP_REQ_DEFAULT_HEADERS: {
    Accept: "application/json",
    "Content-Type": "application/json; charset=UTF-8"
  },
  HTTP_MULTIPART_FORM_HEADERS: {
    "Content-Type": "multipart/form-data"
  },
  HTTP_METHODS: {
    POST: "POST",
    GET: "GET",
    DELETE: "DELETE",
    PATCH: "PATCH",
    PUT: "PUT"
  },
  ONBOARD_STRING: {
    ORGCODE: "Organization Code",
    ORGNAME: "Organization Name",
    CINNUMBER: "CIN Number",
    GSTNUMBER: "GST Number",
    DOMAINNAME: "Domain Name",
    ADDRESSLINE1: "Address Line 1",
    ADDRESSLINE2: "Address Line 2",
    PHONE: "Phone",
    CITY: "City",
    STATE: "State",
    PINCODE: "PIN Code",
    COUNTRY: "Country",
    USERROLE: "User Role",
    NAME: "Name",
    EMAILID: "Email Address",
    PHONENUMBER: "Phone Number",
    EMPLOYES: "No. of Employees"
  },
  HTTP_REQ_ERROR_MAP: {
    401: { status: 401, message: messages.NOT_AUTHORIZED },
    403: { status: 403, message: messages.ACCESS_DENIED },
    404: { status: 404, message: messages.NO_DATA_AVAILABLE }
  },
  POINTS_MODULE: {
    MY_EL_POINTS: "My EL Points",
    POINT_USED_THIS_MONTH: "Points used this month",
    POINT_EARNED_THIS_MONTH: "Points earned this month"
  },
  APPROVAL_LABEL: "Approval",
  ACTIVITY_LOG_LABEL: "My Activity Log",
  ROLES: {
    ADMIN: "admin",
    HRBP: "HR BP",
    EMPLOYEE: "Employee"
  },
  REMEMBER_ME_LABEL: "Remember me",
  FORGOT_PASSWORD_LABEL: "Forgot password?",
  LOG_IN_LABEL: "Login",
  LOGOUT_LABEL: "Logout",
  PROFILE_LABEL: "Profile",
  SETTINGS_LABEL: "Settings",
  REPORTS_LABEL: "Reports",
  NOTIFICATIONS_LABEL: "Notifications",
  ONBOARD_ORG_LABEL: "Onboard Organization",
  VIEW_ORG_LABEL: "View Organization",
  ONBOARD_EMP_LABEL: "Onboard Employee",
  VIEW_EMP_LABEL: "View Employee",
  POINTS_CONFIG_LABEL: "Points Configuration",
  REWARD_CONFIG_LABEL: "Reward Configuration",
  ANNOUNCEMENT_LABEL: "Announcement",
  POPOVER: "popover",
  MYACCOUNT_LABEL: "My Account",
  ADDUSER: "Add User",
  ORGANIZATION: "Organization Onboarding",
  VIEWORGANIZATION: "View all Organization",
  VIEWORG: "ORGANIZATION  DETAILS",
  ORGDHEADER: "View all Organization",
  ORGUSER: "Organization Access",
  SAVEBTN: "SAVE",
  CANCELBTN: "CANCEL",
  UPDLOADDESC: "Upload logo. Use the 200 x 200 pixel size image. PNG or JPEG file format accepted",
  UPLOAD: "Upload",
  SUBHEADER: "For system support please contact your on-site super Admin",
  PHNUMBER: "+91 1128827465",
  PASSWORD: {
    NEWPASSWORD: "Enter your new password",
    CONFORMPASSWORD: "Confirm your new password",
    OLDPASSWORD: "Enter your old password"
  },
  ACTIVATE: "Activated",
  DEACTIVATE: "Disabled",
  PENDING: "Pending",
  REACTIVATE: "Reactivate",
  GUEST_LABEL: "Guest",
  WELCOME_LABEL: "Welcome",
  LOGIN_TITLE: "Login to your Account!",
  EMAIL_LABEL: "Email address",
  EMAIL_PLACEHOLDER: "Please enter email",
  PASSWORD_LABEL: "Enter password",
  PASSWORD_PLACEHOLDER: "Please enter  password",
  LEFT_AREA_TEXT: "EngageLoop is a unique B2B2C Employee Engagement Enabler platform that creates a vast array of options for Employers to effectively deliver their employee engagement related services and employee benefits",
  SECURED_TEXT: "Your Info is safely secured",
  PRIVACY_TEXT: "Privacy Policy",
  COPYRIGHT: "© EngageLoop. All rights reserved.",
  LOGIN_BACK_LABEL: "Back to Login",
  ACTIVATEACCOUNT_TITLE: "Activate your Account",
  ACTIVATEACCOUNT_DESC: "Enter your password to active your account.",
  NEW_PASSWORD_LABEL: "New Password",
  CONFIRM_PASSWORD_LABEL: "Confirm Password",
  OLD_PASSWORD_LABEL: "Old Password",
  ACTIVATEACCOUNT: "Activate account",
  FORGOT_PASSWORD_TITLE: "Forgot Password",
  FORGOT_PASSWORD_DESC: "Send link to your email to reset password",
  FORGOT_PASSWORD_BUTTON: "Reset Password",
  RESET_PASSWORD: "Reset Password",
  RESET_PASSWORD_DESC: "Please choose your password",
  RESET_PASSWORD_BUTTON: "Save new password",
  ORGVIEW_OVERLAY: {
    CODE: "Code:",
    GSTIN: "GSTIN:",
    CIN: "CIN:",
    DOMAIN: "Domain:",
    ADDRESS: "Address",
    USERS: "Users Access",
    LOGO: "Company Logo",
    DETAILS: "Details",
    PHONE: "Phone:"
  },
  EMPLOYE_OPTION_1: "Less than 500",
  EMPLOYE_OPTION_2: "More than 500",
  DISABLE_MESSAGE: "Are you sure to disable the organization?",
  EMPLOYEE: {
    ONBOARDEMP: "Onboard Employee",
    VIEWEMP: "View all Employees",
    EMPDETAILS: "Employee Details",
    FIRSTNAME: "First Name",
    MIDDLENAME: "Middle Name",
    LASTNAME: "Last Name",
    OFFICALEMAILADDRESS: "Offical Email Address",
    PHONENUMBER: "Phone Number",
    MANAGEREMAILADDRESS: "Manager's Email Address",
    IMPORT: "Import",
    TOTALUSERS: "Total Users",
    EMPLOYEEID: "Employee ID",
    JOBLEVEL: "Job Level",
    DESIGNATION: "Designation"
  },
  SUBMENU_KEY_1: "orgboard",
  SUBMENU_KEY_2: "vieworg",
  IMPORT: {
    IMPORT_TITLE: "Import Employee Data",
    FILE_TEXT: "Choose the file to be imported",
    FILE_FORMAT: "[only csv formats are supported]",
    FILE_SIZE: "Maximum upload file size is 5 MB",
    UPLOAD_BTN: "Upload File",
    DOWNLOAD_TEXT: "Download sample template for Import"
  },
  CONFIRM: "CONFIRM",
  SETTINGS_TITILE: "Settings",
  COOKIE_PRERENCES_TITILE: "Cookie Preferences",
  TERMS_CONDITIOND_TITILE: "Terms & Conditions",
  PRIVACYPOLICY_TITILE: "Privacy Policy",
  CONTACTUS_TITILE: "Contact Us",
  USERPROFILE: "User Profile",
  CHANGEPASSWORD_TITLE: "Change Password",
  CHANGEPASSWORD_DESC: "Please choose your password",
  OLD_PASSWORD: "Old Password",
  CHANGEPASSWORD: "Reset Password",
  LOGIN_ERROR: {
    CONTACT_ADMIN: "Please input correct email address/password",
    ORG_FAILED: "Organization not onboarded"
  },
  MAIL: "mailto:customerops@engageloop.in",
  USER_FEEDBACK: "User Feedback"
};

export default constants;
